Repository AGH-Narzedzia-Informatyczne-2023-2024/hot_water_bottle, pull requests merged in 2023-11, with the labels that each got.

#13 zrobiłem funkcję zmiany trybu
  src/przycisk_tryba.ino
Labels: enhancement

#10 Create example.ino
  src/other/example.ino
Labels: enhancement, good first issue

#27 Update new_conflict.txt
  src/other/new_conflict.txt
Labels: bug
